name: PaperExchangeRate
version: '{version}'
main: net.nullpointer.exchange.PaperExchangeRate
api-version: '1.18'
authors: [ NullPointer ]
description: PaperExchangeRate - Fetch actual exchange rate and convert currencies!
softdepend:
  - PlaceholderAPI
commands:
  rate:
    usage: /rate [base] [target]
    description: Gets exchange rate
    permission: exchange.rate
  convert:
    usage: /convert [base] [target] [value]
    description: Convert currency
    permission: exchange.convert
  paperexchangerate:
    usage: /paperexchangerate
    description: Reload configuration
    aliases: [ per ]
    permission: exchange.reload